version: '3.9'

services:
  restaurant-order-svc:
    image: restaurant-order-svc
    networks:
      - restaurant
    container_name: restaurant-order-svc
    build:
      dockerfile: Dockerfile
    ports:
      - "3118:3118"
      - "80:8080"
    healthcheck:
      # test: ["CMD", "bin/grpc_health_probe-linux-amd64", "-addr=localhost:3118", "||", "echo %errorlevel%"]
      test: curl --fail http://localhost:8080/health/ready || exit 1
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 5
networks:
  restaurant:
    name: restaurant-dev-net
    external: true