on:
  push:
    paths-ignore:
      - '**/**.md'
      - 'docs/**'
  pull_request:

env:
  SEMANTIC_VERSION: 0.1.${{github.run_number}}

concurrency: ci-${{ github.ref }}

name: ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ env.SEMANTIC_VERSION }}
    - name: Test
      run: dotnet test --no-build --no-restore -c Release -p:Version=${{ env.SEMANTIC_VERSION }} --verbosity normal --collect:"XPlat Code Coverage" --settings Tests/coverlet.runsettings
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        flags: unittest
        fail_ci_if_error: true
        verbose: true
